name: build & deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: check fmt
      run: cargo fmt --check

    - name: build workspace
      run: cargo build --verbose

    - name: run tests
      run: cargo test --verbose

  deploy:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1.2.1
      - name: install cargo lambda
        run: cargo install cargo-lambda

      - name: build lambda
        run: cargo lambda build --release --arm64
        working-directory: magic_lambda

      - name: deploy lambda
        run: cargo lambda deploy --binary-name magic_lambda
