name: build & deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check fmt
        run: cargo fmt --verbose --all --check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build workspace
      run: cargo build --verbose --workspace

    - name: run tests
      run: cargo test --verbose --workspace

  deploy:
    needs: [build, checks]
    # if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-north-1
        role-to-assume: arn:aws:iam::058264458269:role/lambda-accessor

    - name: install cargo lambda
      run: pip3 install cargo-lambda

    - name: build lambda
      run: cargo lambda build --verbose --release
      working-directory: magic_lambda

    - name: deploy lambda
      run: cargo lambda deploy --verbose --binary-name magic_lambda
      working-directory: magic_lambda
