name: Check workspace

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check fmt
      run: cargo fmt --check
    - name: Build workspace
      run: cargo build --verbose
    - name: Build lambda
      run: cargo lambda build
    - name: Run tests
      run: cargo test --verbose
