name: Check workspace

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:


    - name: Check fmt
      run: cargo fmt --check

    - name: Build workspace
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
